# Problem Statement
The mtcars dataset contains information about different car models and their technical specifications such as mileage, horsepower, weight, number of cylinders, and transmission type.

### Objective:
* import and inspect the dataset
* clean and understand the data
* perform basic and intermediate analysis
* create charts
* write observations
* upload the work to GitHub

In [2]:
import pandas as pd
from pydataset import data

In [3]:
mtcars = data('mtcars')
mtcars.head(5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## Data Exploration

In [4]:
mtcars.shape

(32, 11)

In [5]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [6]:
mtcars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [7]:
print(mtcars.isnull().sum(axis=0), '\n\n', mtcars.isnull().sum(axis=1))

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

 Mazda RX4              0
Mazda RX4 Wag          0
Datsun 710             0
Hornet 4 Drive         0
Hornet Sportabout      0
Valiant                0
Duster 360             0
Merc 240D              0
Merc 230               0
Merc 280               0
Merc 280C              0
Merc 450SE             0
Merc 450SL             0
Merc 450SLC            0
Cadillac Fleetwood     0
Lincoln Continental    0
Chrysler Imperial      0
Fiat 128               0
Honda Civic            0
Toyota Corolla         0
Toyota Corona          0
Dodge Challenger       0
AMC Javelin            0
Camaro Z28             0
Pontiac Firebird       0
Fiat X1-9              0
Porsche 914-2          0
Lotus Europa           0
Ford Pantera L         0
Ferrari Dino           0
Maserati Bora          0
Volvo 142E             0
dtype: int64

In [8]:
mtcars.duplicated().sum()

np.int64(0)

### Analysis
Dataset describes a sample of cars and their aspects:
* mpg = Miles/(US) gallon
* cyl = Number of cylinders
* disp = Displacement (cu.in.)
* hp = Gross horsepower
* drat = Rear axle ratio
* wt = Weight in 1000 lbs
* qsec = 1/4 mile time
* vs = Engine (0 = V-shaped, 1 = straight)
* am = Transmission (0 = automatic, 1 = manual)
* gear = Number of forward gears
* carb = number of carburetors

# Data Cleaning
To get better results, we will clean up the dataset by categorizing and mapping the non continuous or binary datatypes such as cyl, vs, am, gear, and carb. Furthermore, we will categorize HP, Mpg, and weight to bins.

In [9]:
# creating a copy for backup
mtcars_copy = mtcars.copy()

In [17]:
# binding the categorized values in new column
key = {'cyl': "Cylinders", 'gear':"Gears", 'carb':"Carburetors"}
for i in key:
    mtcars[key[i]] = mtcars[i].astype('category')
mtcars.dtypes

mpg             float64
cyl               int64
disp            float64
hp                int64
drat            float64
wt              float64
qsec            float64
vs                int64
am                int64
gear              int64
carb              int64
Cylinders      category
Gears          category
Carburetors    category
dtype: object

In [19]:
# mapping vs and am
mtcars['Engine Shape'] = mtcars['vs'].map({0:'Vshaped', 1:'Straight'})
mtcars['Transmission'] = mtcars['vs'].map({0:'Automatic', 1:'Manual'})
mtcars.dtypes

mpg              float64
cyl                int64
disp             float64
hp                 int64
drat             float64
wt               float64
qsec             float64
vs                 int64
am                 int64
gear               int64
carb               int64
Cylinders       category
Gears           category
Carburetors     category
Engine Shape      object
Transmission      object
dtype: object

In [22]:
mtcars[['hp', 'mpg', 'wt']].describe()

               hp        mpg         wt
count   32.000000  32.000000  32.000000
mean   146.687500  20.090625   3.217250
std     68.562868   6.026948   0.978457
min     52.000000  10.400000   1.513000
25%     96.500000  15.425000   2.581250
50%    123.000000  19.200000   3.325000
75%    180.000000  22.800000   3.610000
max    335.000000  33.900000   5.424000

In [24]:
## Putting important car aspects into bins
# HP
mtcars['HP class'] = pd.cut(mtcars['hp'], bins=[0, 100, 180, 250, mtcars['hp'].max()], labels=['Very Low', 'Low', 'Medium', 'High'], include_lowest=True)
# MPG
mtcars['Fuel Consumption class'] = pd.cut(mtcars['mpg'], bins=[0, 15, 21, 27, mtcars['mpg'].max()], labels=['High', 'Medium', 'Low', 'Very Low'], include_lowest=True)
# Weight
mtcars['Weight class'] = pd.cut(mtcars['wt'], bins=[0, 2, 3.2, 4, mtcars['mpg'].max()], labels=['Light', 'Medium', 'Heavy', 'Very Heavy'], include_lowest=True)
mtcars.head(mtcars.shape[0])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Cylinders,Gears,Carburetors,Engine Shape,Transmission,HP class,Fuel Consumption class,Weight class
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,6,4,4,Vshaped,Automatic,Low,Medium,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,6,4,4,Vshaped,Automatic,Low,Medium,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,4,4,1,Straight,Manual,Very Low,Low,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,6,3,1,Straight,Manual,Low,Low,Heavy
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8,3,2,Vshaped,Automatic,Low,Medium,Heavy
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,6,3,1,Straight,Manual,Low,Medium,Heavy
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,8,3,4,Vshaped,Automatic,Medium,High,Heavy
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,4,4,2,Straight,Manual,Very Low,Low,Medium
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,4,4,2,Straight,Manual,Very Low,Low,Medium
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,6,4,4,Straight,Manual,Low,Medium,Heavy
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,6,4,4,Straight,Manual,Low,Medium,Heavy
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8,3,3,Vshaped,Automatic,Low,Medium,Very Heavy
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8,3,3,Vshaped,Automatic,Low,Medium,Heavy
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,8,3,3,Vshaped,Automatic,Low,Medium,Heavy
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8,3,4,Vshaped,Automatic,Medium,High,Very Heavy
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8,3,4,Vshaped,Automatic,Medium,High,Very Heavy
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8,3,4,Vshaped,Automatic,Medium,High,Very Heavy
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,4,4,1,Straight,Manual,Very Low,Very Low,Medium
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,4,4,2,Straight,Manual,Very Low,Very Low,Light
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,4,4,1,Straight,Manual,Very Low,Very Low,Light
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,4,3,1,Straight,Manual,Very Low,Low,Medium
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8,3,2,Vshaped,Automatic,Low,Medium,Heavy
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8,3,2,Vshaped,Automatic,Low,Medium,Heavy
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,8,3,4,Vshaped,Automatic,Medium,High,Heavy
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8,3,2,Vshaped,Automatic,Low,Medium,Heavy
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,4,4,1,Straight,Manual,Very Low,Very Low,Light
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,4,5,2,Vshaped,Automatic,Very Low,Low,Medium
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,4,5,2,Straight,Manual,Low,Very Low,Light
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,8,5,4,Vshaped,Automatic,High,Medium,Medium
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,6,5,6,Vshaped,Automatic,Low,Medium,Medium
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,8,5,8,Vshaped,Automatic,High,High,Heavy
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,4,4,2,Straight,Manual,Low,Low,Medium